on: [push, pull_request]
name: Test
jobs: 
  Test:
    runs-on: ubuntu-20.04
    container: golang:1.16beta1-alpine3.12
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        stable: false
        go-version: 1.16.0-beta1

    - name: Test
      run: go test ./...
      env: 
        CGO_ENABLED: 0